version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
