version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  mc:
    image: minio/mc:RELEASE.2020-04-25T00-43-23Z
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      mc config host add super-puper-config http://minio:9000 minio minio123 && \
        mc mb super-puper-config/default || exit 1;"

  bysykkel2minio:
    image: zhenik/bysykkel2minio:proxy-1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      BYSYKKEL_CLIENT_IDENTIFIER: zhenik-test
      BYSYKKEL_API_URL: https://gbfs.urbansharing.com/oslobysykkel.no/station_status.json
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKETNAME: default
      MINIO_BUCKETNAME_SUFFIX:  bysykkel/station-availability/
#      optional
#      PROXY_URI:
#      PROXY_PORT:
#      PROXY_SCHEME:
    depends_on:
      - minio
      - mc
